WITH RECURSIVE sundaysInAnYear AS (
SELECT CAST(CONCAT(YEAR(CURDATE()),'-01-01') AS DATE) AS thisDate, CAST(CONCAT(YEAR(CURDATE())+1,'-01-01') AS DATE) AS lastDate,
DAYOFWEEK( CAST(CONCAT(YEAR(CURDATE()),'-01-01') AS DATE)) as weekDay
UNION ALL
SELECT DATE_ADD(thisDate, INTERVAL 1 DAY) AS thisDate,
lastDate,
DAYOFWEEK(DATE_ADD(thisDate, INTERVAL 1 DAY)) as weekDay FROM sundaysInAnYear
WHERE
DATE_ADD(thisDate, INTERVAL 1 DAY) < lastDate )SELECT COUNT(*) FROM sundaysInAnYear WHERE weekDay=1;